language: node_js
node_js:
- 6.11.0
script: mocha --timeout 10000 --recursive --reporter list
before_script:
- npm install
after_success:
- npm run coveralls
- test $TRAVIS_BRANCH = "master_desativado" && test $TRAVIS_PULL_REQUEST = "false" && now -t
  $TOKEN_NOW --public
- test $TRAVIS_BRANCH = "master_desativado" && test $TRAVIS_PULL_REQUEST = "false" && now -t
  $TOKEN_NOW --public alias
before_install:

